language: node_js
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
node_js:
  - "8"
python:
  - "2.7"
cache:
  yarn: true
  directories:
    - node_modules
script:
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - yarn run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "pressminder-web"
  acl: public_read
  local_dir: build
  skip_cleanup: true
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

