language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
script:
before_install:
  - npm install -g aws-cli
install:
  - yarn run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "pressminder-web"
  acl: public_read
  local_dir: build
  skip_cleanup: true
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

